[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "node dist/server/index.js"
restartPolicy = "ON_FAILURE"
numReplicas = 1
healthcheckPath = "/api/health"
healthcheckTimeout = 300

[[services]]
internal_port = 5173
protocol = "tcp"

[services.concurrency]
type = "connections"
hard_limit = 25
soft_limit = 20

[[services.ports]]
port = "5173"
handlers = ["http"]

[services.environment]
NODE_ENV = "production"
PORT = "5173"
HOST = "0.0.0.0"

[nixpacks]
node-version = "18"